### ISSUE TITLE
How would I parse a value with curly brackets?

### ISSUE THREAD

**Issue by kalekje** [Josef-Friedrich/luakeys#10]
I desire the following output:
```
luakeys.parse('hello={world}') -> hello='{world}'
```

How can I achieve this?

**Comment by Josef-Friedrich** [comment]
You have to use double quotes:

```
luakeys.parse('hello="{world}"')
```

**Comment by kalekje** [comment]
Is there any provision in the settings for this without quotes? One example I can think of is setting a key to a LaTeX command value?
`format=\color{blue}` would be nice syntax vs. `format="\color{blue}"`

**Comment by Josef-Friedrich** [comment]
> Is there any provision in the settings for this without quotes? 

Unfortunately not. For this the LPeg grammar would have to be adapted. I think that is not an easy task.

**Comment by kalekje** [comment]
That's understandable, thanks for considering.
