### ISSUE TITLE
Feature request: change delimiter from comma

### ISSUE THREAD

**Issue by kalekje** [Josef-Friedrich/luakeys#13]
Although I appreciate that it's unconventional, I think the ability to change the delimiter from a comma to something else (semicolon; comes to mind) would be helpful.

**Comment by Josef-Friedrich** [comment]
Thank you for your request. A semicolon as a delimiter is in my opinion not unconventional

**Comment by kalekje** [comment]
Great--i haven't seen it be used in LaTeX, but I think it would help, especially if users have a lot of commas in their values to avoid wrapping in quotes each time. I think from a coding perspective it shouldn't be too challenging to implement

**Comment by Josef-Friedrich** [comment]
I have added these options:

```lua
  opts = {
    group_begin = '{',
    group_end = '}',
    list_separator = ',',
    assignment_operator = '=',
    quotation_begin = '"',
    quotation_end = '"'
  },
```

**Comment by kalekje** [comment]
Very nice! TYVM!

**Comment by Josef-Friedrich** [comment]
I have just uploaded version 0.8.0 to CTAN
