### ISSUE TITLE
Feature request: convert booleans with aliases like on/yes or off/no

### ISSUE THREAD

**Issue by kalekje** [Josef-Friedrich/luakeys#17]
It's common for many kv interfaces to have aliases for booleans. I would propose that this be an option, and if present, yes or on is converted to true, and no or off is converted to false.

**Comment by Josef-Friedrich** [comment]
something like this?

```lua
local result = luakeys.parse('key=yes', {
  true_aliases = { 'true', 'TRUE', 'True', 'on', 'yes' },
  false_aliases = { 'false', 'FALSE', 'False', 'off', 'no' },
})
luakeys.debug(result) -- { key = true }
```

**Comment by kalekje** [comment]
Yes I think an interface like that would be great!
