### ISSUE TITLE
Feature request: option on how to process standalone values

### ISSUE THREAD

**Issue by kalekje** [Josef-Friedrich/luakeys#5]
I think a few of us might want an option on how to process standalone values. I think under the `luakeys.parse` options table, an option for `standaloneastrue` might be nice--instead of storing standalone values as integer-indexed values, I would like to see them as keys with a value set to true.

Ex: `a,b,c,X=1,Y=2,Z=3` would produce a table like so:

```
Y	2
b	true
Z	3
c	true
X	1
a	true
```

I made a simple function to patch this up for my own use.

```
    local t_new = {}
    for k, v in pairs(t) do
        if type(k) == 'number' then
            t_new[v] = true
        else
            t_new[k] = v
        end
    end
    return t_new
```

**Comment by Josef-Friedrich** [comment]
I added a new option called `standalone_as_key`

**Comment by kalekje** [comment]
I looked through the code and I think it's actually called `standalone_as_true`, something to keep in mind if you update the documentation. Thanks for adding this feature--I will have to test if it works for nested key-vals as well. To me, parsing key-val options as LaTeX options makes sense this way. But the default was is great if you want a Lua table (maybe you want to declare a table in TeX) because the syntax maps basically 1 to 1. Very nice!

**Comment by Josef-Friedrich** [comment]
Maybe `standalone_as_key` or even `standalone_string_as_key` is a better name for this option. `standalone_as_true` should work recursively.

Maybe the following new option (a callback function / hook) is also interesting for you:

```lua
luakeys.parse(
  'one,two,three={four}',
  {
    converter = function (key, value, depth, current_table, root_table)
      if type(key) == 'number' and type(value) == 'string' then
        return value, true -- the value is now key, true is now the new value
      end
      return key, value -- return key, value to change nothing
    end
  }
)

--> {one = true, two = true, three = {four = true}}
```

**Comment by kalekje** [comment]
Interesting--I like that converter option.

**Comment by kalekje** [comment]
I can't seem to find this feature anymore in the source code.. did you
remove it?

**Comment by Josef-Friedrich** [comment]
The feature still exists. Check out this lines:

https://github.com/Josef-Friedrich/luakeys/blob/6d5e6764a41d78d3e7a798eaba2dea8c306fdd51/luakeys.lua#L461-L463

**Comment by kalekje** [comment]
So now I have to provide it with that function? Is there any chance you
could include the original request (standalone_as_true) as a valid option?
I think it's general and useful enough to include as a built-in capability.

**Comment by Josef-Friedrich** [comment]
I think there was a misunderstanding. I have added the additional option `converter` that might be useful for you. I have implemented the option `standalone_as_true` as you requested.

https://github.com/Josef-Friedrich/luakeys/blob/6d5e6764a41d78d3e7a798eaba2dea8c306fdd51/luakeys.lua#L369-L371

https://github.com/Josef-Friedrich/luakeys/blob/9593ab455f523b2b1ce4c274baf9c12d59ca7260/test/lua/public-functions.lua#L105-L116

However, the documentation is still missing

**Comment by kalekje** [comment]
Ahh thank you. I had an outdated version and not seeing it in the
documentation confused me. Thank you!

**Comment by Josef-Friedrich** [comment]
Breaking change in v0.6

Standalone values are now interpreted as naked keys by default and set to true. To get the old behavior back us `{ naked_as_value = true }`
