### ISSUE TITLE
Documentation section 5.2 - Class Options Example 

### ISSUE THREAD

**Issue by kalekje** [Josef-Friedrich/luakeys#8]
![image](https://user-images.githubusercontent.com/51413662/187719080-bce498c9-1cdb-49e3-8ae5-ca61247c2b87.png)

In this example, `naked_as_value=true` is not present in the options, so I believe the resultant table should be `{'12pt'=true,'landscape'=true}`

**Comment by Josef-Friedrich** [comment]
Thank you for reporting the error. However, I will not upload a new version to CTAN yet.
